// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ejcpdupcgnifayvmckew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVqY3BkdXBjZ25pZmF5dm1ja2V3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxNjk1NjYsImV4cCI6MjA2Mzc0NTU2Nn0.S4zzDu9u67pkx55YgnOXoKitoNzWEHt7w9rVCKnUuRo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);